version: "3.2"

services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    env_file:
      - ./mariadb.env
    networks:
      - glpi-network

  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
    networks:
      - glpi-network

  sqlserver:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: ${SQL_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: 
    - sqldata:/var/opt/mssql
    networks:
      - sqlserver-network

volumes:
  sqldata:
  glpi:
  mariadbdata:

networks:
  glpi-network:
  sqlserver-network:
