version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels

  sqlserver:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: 
    - sqldata:/var/opt/mssql

volumes:
  sqldata:
  glpi: